In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 1.2 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.6 MB 1.2 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/12.6 MB 1.0 MB/s eta 0:00:12
   ---- ----------------------------------- 1.3/12.6 MB 1.2 MB/s eta 0:00:10
   ---- ----------------------------------- 1.6/12.6 MB 1.2 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/12.6 MB 1.2 MB/s eta 0:00:09
   ------ --------------------------------- 2.1/12.6 MB 1.2 MB/s eta 0:00:09
   ------- -------------------------------- 2.4/12.6 MB 1.3 MB/s eta 0:00:09
   --------- ------------------------------ 2.9/12.6 MB 1.3 MB/s eta 0:00:08
   --------- ------------------------------ 3.1/12.6 MB 1.3 MB/s eta 0:00:08
   ---------- ------


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [2]:
np.array([1,3,2,5,6])

array([1, 3, 2, 5, 6])

In [3]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
np.array([1,2,3,4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [5]:
np.array([range(i,i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.random.random((3,3))

array([[0.73658531, 0.80674397, 0.29641862],
       [0.33963054, 0.00743049, 0.59801067],
       [0.18915208, 0.82648276, 0.44945271]])

In [12]:
np.random.normal(0,1,(3,3))

array([[ 1.20845768,  0.92338115, -1.21705846],
       [ 0.58331909, -0.00401623, -0.96604151],
       [-0.55415477,  0.46704363, -0.25235192]])

In [16]:
np.random.randint(0,10,(3,3))

array([[7, 2, 2],
       [0, 9, 7],
       [2, 4, 4]], dtype=int32)

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.empty(3)

array([1., 1., 1.])