In [1]:
import numpy as np

In [7]:
rng = np.random.default_rng(seed=1701)

x1 = rng.integers(10, size=6)
x2 = rng.integers(10, size=(3, 4))
x3 = rng.integers(10, size=(3, 4, 5))

print(x1)
print(x2)
print(x3)

[9 4 0 3 8 6]
[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
[[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]


In [8]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("dtype:", x3.dtype)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
dtype: int64


In [9]:
print(x1)
print(x1[4])
print(x1[-1])

[9 4 0 3 8 6]
8
6


In [11]:
print(x2)
print(x2[0,0])
print(x2[2,0])
print(x2[2,-1])

[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
3
0
9
