In [2]:
import numpy as np

In [3]:
# 先設定一個seed 確保每一次程式碼執行時都會產生相同的亂數陣列
rng = np.random.default_rng(seed=1701)

x1 = rng.integers(10, size=6)
x2 = rng.integers(10, size=(3, 4))
x3 = rng.integers(10, size=(3, 4, 5))

print(x1)
print(x2)
print(x3)

[9 4 0 3 8 6]
[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
[[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]


In [4]:
# 每個陣列都有  ndim (維度) shape (每一個維度的大小) size (整個陣列的元素數) dtype (資料型態)
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("dtype:", x3.dtype)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
dtype: int64


In [5]:
# 以一維陣列為例 一樣是用中括號取值 從0開始算 也可以倒著算從-1開始算
print(x1)
print(x1[4])
print(x1[-1])

[9 4 0 3 8 6]
8
6


In [6]:
# 多維陣列的話  依照維度給索引
print(x2)
print(x2[0,0])
print(x2[2,0])
print(x2[2,-1])

[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
3
0
9


In [8]:
# 取一維子陣列
print(x1)
print(x1[:3]) # 前三個元素
print(x1[3:]) # 在索引3後的元素
print(x1[1:4]) # 中間的子陣列
print(x1[::2]) # 間隔2的所有元素
print(x1[1::2]) # 從索引1開始間隔2的所有元素

[9 4 0 3 8 6]
[9 4 0]
[3 8 6]
[4 0 3]
[9 0 8]
[4 3 6]


In [9]:
# 取多維子陣列 其實也是一樣的方式 只是每一維度都要指定
print(x2)
print(x2[:2, :3]) # 前兩列以及前三欄
print(x2[:3, ::2]) # 前三列以及間隔為2的欄
print(x2[::-1, ::-1]) # 反向取出所有列和欄的值

[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
[[3 1 3]
 [4 0 2]]
[[3 3]
 [4 2]
 [0 6]]
[[9 6 0 0]
 [3 2 0 4]
 [7 3 1 3]]


In [12]:
print(x2[:,0]) # 取出每列第一欄的值 輸出為陣列
print(x2[0,:]) # 取出第一列
print(x2[0]) # 第一個維度的所有資料 可以省略後面的宣告

[3 4 0]
[3 1 3 7]
[3 1 3 7]


In [13]:
# Numpy取出的子陣列並非是複製一份新的資料而是直接讓你取用的值
print(x2)

x2_sub = x2[:2, :2]
print(x2_sub)

x2_sub[0,0] = 99
print(x2_sub)

print(x2)

[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
[[3 1]
 [4 0]]
[[99  1]
 [ 4  0]]
[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [15]:
print(x2)

x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

print(x2) #原始內容不會被動到

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]
[[99  1]
 [ 4  0]]
[[42  1]
 [ 4  0]]
[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [16]:
# 一維轉二維
grid = np.arange(1, 10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
x = np.array([1, 2, 3])
print(x.reshape((1,3))) # 建立列向量

print(x.reshape((3,1))) # 建立欄向量

print(x[np.newaxis, :])

print(x[:, np.newaxis])

[[1 2 3]]
[[1]
 [2]
 [3]]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [20]:
# 串接兩個陣列
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x, y]))

# 串接2個以上的陣列
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

# 串接二維陣列
grid = np.array([[1, 2, 3],
                [4, 5, 6]])

# 沿著第一軸串接
print(np.concatenate([grid, grid]))

# 沿著第二軸串接
print(np.concatenate([grid, grid], axis=1))

# 垂直地堆疊在陣列上
print(np.vstack([x, grid]))

# 水平地堆疊在陣列上
y = np.array([[99],
             [99]])
print(np.hstack([grid, y]))


[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [1 2 3]
 [4 5 6]]
[[ 1  2  3 99]
 [ 4  5  6 99]]


In [21]:
# 指定要分割的陣列跟分割點
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x,[3, 5])
print(x1, x2, x3)

grid = np.arange(16).reshape((4,4))
print(grid)

# 沿垂直方向分割
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)


# 沿水平方向分割
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[1 2 3] [99 99] [3 2 1]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
