In [2]:
import numpy as np

In [4]:
x = np.arange(4)
print(x)
print(x+5)
print(x-5)
print(x*2)
print(x/2)
print(x//2) #取地板的除號(整除)
print(-x)
print(x**2)
print(x%2)
print(-(0.5*x +1) **2)

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]
[ 0 -1 -2 -3]
[0 1 4 9]
[0 1 0 1]
[-1.   -2.25 -4.   -6.25]


In [5]:
x = np.arange(4)
print(np.add(x,5))
print(np.subtract(x,5))
print(np.multiply(x,2))
print(np.divide(x,2))
print(np.floor_divide(x,2))
print(np.negative(x))
print(np.power(x,2))
print(np.mod(x,2))

[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]
[ 0 -1 -2 -3]
[0 1 4 9]
[0 1 0 1]


In [7]:
x = np.array([-2, -1, 0, 1, 2])
print(abs(x))
print(np.abs(x))
print(np.absolute(x))

x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
print(np.abs(x))

[2 1 0 1 2]
[2 1 0 1 2]
[2 1 0 1 2]
[5. 5. 2. 1.]


In [8]:
theta = np.linspace(0, np.pi, 3)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

x = [-1, 0 ,1]
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


In [9]:
x = np.array([1, 2, 3])
print(x)
print(np.exp(x)) # 以e為底
print(np.exp2(x)) # 以2為底
print(np.power(3., x)) # 3以上用power


[1, 2, 3]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 3.  9. 27.]


In [15]:
x = np.array([1, 2, 4, 10])
print(x)
print(np.log(x)) # 以e為底
print(np.log2(x)) # 以2為底
print(np.log10(x)) # 以10為底

[ 1  2  4 10]
[0.         0.69314718 1.38629436 2.30258509]
[0.         1.         2.         3.32192809]
[0.         0.30103    0.60205999 1.        ]


In [16]:
x = np.array([0, 0.001, 0.01, 0.1])
print(np.expm1(x))
print(np.log1p(x))
print(np.exp(x)-1)
print(np.log(1 +x))

[0.         0.0010005  0.01005017 0.10517092]
[0.         0.0009995  0.00995033 0.09531018]
[0.         0.0010005  0.01005017 0.10517092]
[0.         0.0009995  0.00995033 0.09531018]


In [22]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(x)
print(y)

[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


In [28]:
x = np.arange(5)
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(x)
print(y)

[0 1 2 3 4]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [29]:
x = np.arange(1, 6)
print(x)
print(np.add.reduce(x))
print(np.multiply.reduce(x))
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

[1 2 3 4 5]
15
120
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [34]:
x = np.arange(1,6)
y= np.arange(1,3)
print(x)
print(y)
print(np.multiply.outer(x,y))
print(np.multiply.outer(y,x))
print(np.multiply.outer(x,x))
print(np.multiply.outer(y,y))



[1 2 3 4 5]
[1 2]
[[ 1  2]
 [ 2  4]
 [ 3  6]
 [ 4  8]
 [ 5 10]]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
[[1 2]
 [2 4]]
