In [6]:
import numpy as np

name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

# 在結構陣列中使用複合資料型態
data = np.zeros(4, dtype={'names':('name', 'age','weight'),'formats':('U10', 'i4', 'f8')})
print(data)
print(data.dtype)

[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [7]:
# 將個別陣列資料填入複合資料型態陣列中
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [10]:
print(data['name'])
print(data[0])
print(data[-1]['name'])

# 使用布林遮罩
print(data[data['age']<30]['name'])

['Alice' 'Bob' 'Cathy' 'Doug']
('Alice', 25, 55.0)
Doug
['Alice' 'Doug']


In [12]:
# 前面的為字典建立法
print(np.dtype({'names':('name', 'age','weight'),'formats':('U10', 'i4', 'f8')}))

# 數值型態可以使用python 的type 或 NumPy的 dtype
print(np.dtype({'names':('name', 'age','weight'),'formats':((np.str_, 10), int, np.float32)}))

# 也可以個別指定
print(np.dtype([('name', 'S10'),('age', 'i4'), ('weight', 'f8')]))

# 如果名稱不重要 可以直接以逗點分隔的字串來設定
print(np.dtype('S10,i4,f8'))



[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('name', '<U10'), ('age', '<i8'), ('weight', '<f4')]
[('name', 'S10'), ('age', '<i4'), ('weight', '<f8')]
[('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')]


In [13]:
tp = np.dtype([('id','i8'),('mat','f8',(3,3))])
x = np.zeros(1, dtype=tp)
print(x)
print(x[0])
print(x['mat'][0])

[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# 字典鍵方式
print(data['age'])

# 屬性方式
data_rec = data.view(np.recarray)
print(data_rec.age)

[25 45 37 19]
[25 45 37 19]
